---
title: "Part 1: 데이터 분석 기획의 이해 (Understanding Data Analysis Planning)"
output: rmarkdown::github_document
---

# Table of Contents

- **Chapter 1 - 분석기획 방향성 도출 (Directions for Data Analysis Planning)**
  - 분석기획의 특징
  - 분석 대상과 방법
  - 목표 시점 별 분석 기획 방안
  - 분석 기획시 고려사항
    
- **Chapter 2 - 분석 방법론 (Analysis Methodology)** 
  - 분석 방법론 개요
  - KDD 분석 방법론
  - CRISP-DM 분석 방법론
  - KDD와 CRISP-DM의 비교
  - 빅데이터 분석 방법론
  
- **Chapter 3 - 분석 과제 발굴 (Discovering the Subject of Analysis)**
  - 분석과제 발굴 방법론

- **Chapter 4 - 분석 프로젝트 관리 방안 (Management Plans for Analysis Projects)**
  - 분석과제 관리를 위한 5가지 주요 영역
  - 분석 프로젝트의 특성
  - 분석 프로젝트의 관리방안
  


# Chapter 1 - 분석기획 방향성 도출 (Directions for Data Analysis Planning)

## 1. 분석기획의 특징

#### 가. 분석기획이란?

- 실제 분석을 수행하기에 앞서 분석을 수행할 **과제를 정의**하고, 의도했던 **결과를 도출**할 수 있도록 이를 적절하게 **관리**할 수 있는 방안을 **사전에 계획**하는 일련의 작업
  - 어떠한 **목표(What)** 를 달성하기 위하여
  - 어떠한 **방식(How)** 으로 수행할 지에 대한 일련의 계획을 수립
  
#### 나. 데이터 사이언티스트의 역량

- 분석을 기획한다는 것은 해당 문제 영역에 대한 전문성 역량 및 수학/통계학적 지식을 활용한 분석 역량과 분석의 도구인 데이터 및 프로그래밍 기술 역량에 대한 균형 잡힌 시각을 가지고 방향성 및 계획을 수립한다는 것
  - **Math & Statistics (수학&통계학 지식)**
  - **Information Technology (컴퓨터 사이언스)**
  - **Domain Knowledge (비즈니스 분석능력)**

## 2. 분석 대상과 방법

- **분석 주제의 4가지 유형**

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  **분석의 대상 (What)**  

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Known \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  Un-Known  
**분석의 방법 (How)** \ \ \ \ \ \ \ \ \ \ **최적화 (Optimization)** \ \ \ \ \ \ \ **통찰 (Insight)** \ \ \ \ \ \ \ \ \ \ \ \ Known  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **솔루션 (Solution)** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **발견 (Discovery)** \ \ \ \ \ \ Un-Known  


## 3. 목표 시점 별 분석 기획 방안

**당면한 분석 주제의 해결 (과제 단위)**  

- 1차 목표
  - Speed & Test
- 과제의 유형
  - Quick & Win
- 접근 방식
  - Problem Solving

**지속적 분석 문화 내재화 (마스터 플랜 단위)**

- 1차 목표
  - Accuracy & Deploy
- 과제의 유형
  - Long Term View
- 접근 방식
  - Problem Definition


## 4. 분석 기획시 고려사항

- **고려사항 3가지**
  - 가용한 데이터 (Available Data)
    - 분석을 위한 **데이터 확보**가 우선적, 데이터의 **유형에 따라 적용 가능한 솔루션** 및 **분석 방법** 이 다르기 때문에 유형에 대한 분석이 선행적으로 이루어져야 함
      - **데이터 유형 3가지**
        - **정형 데이터:** ERP, CRM, SCM 등 정보시스템
        - **반정형 데이터:** Machine Data
        - **비정형 데이터:** e-mail, 소셜미디어, blogs and news
  - 적절한 유즈케이스 (Proper Business Use Case)
    - 유사분석 시나리오 및 솔루션이 있다면 이를 최대한 활용하는 것이 중요함
  - 장애요소들에 대한 사전계획 수립 (Low Barrier of Execution)
    - 일회성 분석으로 그치지 않고 조직의 역량을 내재화하기 위해서는 충분하고 계속적인 교육 및 활용방안 등의 **변화관리(Change Management)** 가 고려되어야 함

**예상문제**  
**19.2. 다음 중 "분석과제 정의서"에 대한 설명으로 가장 적절한 것은?**

1. "분석과제 정의서"에는 소스 데이터, 데이터 입수 및 분석의 난이도, 분석방법 등에 대한 항목이 포함되어야 한다  
2. "분석과제 정의서"는 프로젝트를 수행하는 이해관계자가 프로젝트의 방향을 설정하고 성공 여부를 판별할 수 없는 자료이다  
3. "분석과제 정의서"에는 분석모델에 적용 될 알고리즘과 분석모델의 기반이 되는 Feature가 포함되어야 한다  
4. "분석과제 정의서"는 프로젝트 계획서를 작성하기 위한 중간 결과로서 구성목(Configuration Item)으로 도출할 필요는 없다.

(정답):  

**20. 아래 (가)와 (나)에 순서대로 들어갈 내용으로 적절한 것은?**  
<보기> 분석은 분석 대상(What) 및 분석 방법(How)에 따라 4가지로 나눌 수 있다. 분석 대상이 명확하게 무엇인지 모르는 경우에는 기존 분석 방식을 활용하여 (가)을(를) 도출해냄으로써 문제의 도출 및 해결에 기여하거나 (나) 접근법으로 분석 대상 자체를 새롭게 도출할 수 있다.

1. 최적화 - 통찰  
2. 솔루션 - 통찰  
3. 통찰 - 발견  
4. 발견 - 솔루션

(정답): 3번 

**21. "목표시점 별로 당면한 과제를 빠르게 해결하는 (a)와 지속적인 분석 내재화를 위한 (b)로 나눌 수 있다." 여기서 말하는 (a)와 (b)로 맞는 것은?**  


1. (a): 과제 중심적인 접근 방식, (b): 장기적인 마스터 플랜 방식
2. (a): 과제 중심적인 접근 방식, (b): 거버넌스 체계 수행 방식
3. (a): 시험 중심적인 접근 방식, (b): 장기적인 마스터 플랜 방식
4. (a): 시험 중심적인 접근 방식, (b): 거버넌스 체계 수행 방식

(정답): 1번  


# Chapter 2 - 분석 방법론 (Analysis Methodology)

## 1. 분석 방법론 개요

#### 가. 개요

- 데이터 분석이 효과적으로 기업 내에 정착하기 위해서는 이를 **체계화한 절차와 방법**이 정리된 **데이터 분석 방법론의 수립** 이 필수적
- **방법론의 구성요소**
  - 상세한 절차 (Procedure)
  - 방법 (Methods)
  - 도구와 기법 (Tools & Techniques)
  - 템플릿과 산출물 (Templates & Outputs)

#### 나. 데이터 기반 의사결정의 필요성

- **기업의 합리적 의사결정 장애요소**
  - 고정관념 (Stereotype)
  - 편향된 생각 (Bias)
  - 프레이밍효과 (Framing Effect)
    - 문제의 표현 방식에 따라 동일한 사건이나 상황임에도 불구하고 개인의 판단이나 선택이 달라질 수 있는 현상
    
#### 다. 방법론의 생성과정

암묵지 -> 형식지 -> 방법론 -> 암묵지

#### 라. 방법론의 적용 업무의 특성에 따른 모델

- **폭포수 모델 (Waterfall Model)**
  - **단계를 순차적으로 진행하는 방법** 으로, 이전 단계가 완료되어야 다음 단계로 진행될 수 있으며 문제가 발견될 시 피드백 과정이 수행됨
  
- **프로토타입 모델 (Prototype Model)**
  - 폭포수 모델의 단점을 보완하기 위해 점진적으로 시스템을 개발해 나가는 접근 방식
  - **고객의 요구** 를 완전하게 이해하고 있지 못하거나 완벽한 요구 분석의 어려움을 해결하기 위해 **일부분을 우선 개발** 하여 사용자에게 제공
  - 시험 사용 후 사용자의 요구를 분석하거나 요구 정당성을 점검, 성능을 평가하여 **그 결과를 통한 개선 작업**을 시행하는 모델

- **나선형 모델 (Spiral Model)**
  - 반복을 통해 점증적으로 개발하는 방법으로, 처음 시도하는 프로젝트에 적용이 용이하지만 관리 체계를 효과적으로 갖추지 못한 경우 복잡도가 상승하여 프로젝트 진행이 어려울 수 있다

#### 마. 방법론의 구성

**예상문제**  
**22. 분석 방법론 개요로 틀린 것은?**  

1. 정리된 데이터 분석 방법론의 수립은 기업에서 필수적으로 요구되고 있다  
2. 프로젝트는 산출물과 프로젝트 성공 가능성을 보지 않고 개인의 역량으로 판단 한다  
3. 방법론은 상세한 절차, 방법, 도구와 기법, 템플릿과 산출물로 구성되어 있다  
4. 방법론은 어느 정도 지식만 있으면 활용이 가능해야 한다

(정답): 2번  

**23. 다음 중 기업에서 데이터에 기반한 의사결정을 방해하는 요소들로 구성된 것은?**

1. 프레이밍 효과, 비판적 사고  
2. 바이어스, 직관력  
3. 프레이밍 효과, 고정 관념   
4. 고정 관념, 비편향적 사고

(정답): 3번


## 2. KDD 분석 방법론

#### 가. 개요

- **KDD (Knowledge Discovery in Database)**
  - 1996년 Fayyad가 프로파일링 기술을 기반으로 데이터로부터 통계적 패턴이나 지식을 찾기 위해 활용할 수 있도록 체계적으로 정리한 **데이터 마이닝 프로세스**이다

#### 나. KDD 분석 절차

Data -> **Selection** -> Target Data -> **Preprocessing** -> Preprocessed Data -> **Transformation** -> Transformed Data -> **Data Mining** -> Patterns -> **Interpretation/Evaluation** -> Knowledge

- **데이터 선택 (Selection)**
  - 데이터셋 선택에 앞서 분석 대상의 **비즈니스 도메인**에 대한 이해와 **프로젝트 목표 설정**이 필수이며 데이터베이스 또는 원시 데이터에서 분석에 필요한 데이터를 선택하는 단계
  - 데이터마이닝에 필요한 **목표데이터(target data)** 를 구성하여 분석에 활용
  
- **데이터 전처리 (Preprocessing)**
  - 추출된 분석 대상용 데이터 셋에 포함되어 있는 **잡음(Noise)** 과 **이상치(Outlier)**, **결측치(Missing Value)** 를 식별하고 필요시 제거하거나 의미있는 데이터를 재처리하여 데이터 셋을 정제하는 단계
  - 데이터 전처리 단계에서 **추가로 요구되는 데이터** 셋이 필요한 경우 데이터 선택 프로레스를 실행한다

- **데이터 변환 (Transformation)**
  - 데이터 전처리 과정을 통해 정제된 데이터에 분석 목적에 맞게 변수를 생성, 선택하고 **데이터의 차원을 축소**하여 효율적으로 데이터마이닝을 할 수 있도록 데이터에 변경하는 단계
  - 데이터마이닝 프로세르를 진행하기 위해 **학습용 데이터(training data)** 와 **검증용 데이터(test data)** 로 데이터를 분리하는 단계

- **데이터 마이닝 (Data Mining)**
  - 학습용 데이터를 이용하여 분석목적에 맞는 **데이터마이닝 기법을 선택**하고, 적절한 알고리즘을 적용하여 데이터마이닝 작업을 실행하는 단계
  - 필요에 따라 데이터 **전처리** 와 데이터 **변환** 프로세스를 추가로 실행하여 최적의 결과를 산출

- **데이터 마이닝 결과 평과 (Interpretation/Evaluation)**
  - 데이터마이닝 **결과에 대한 해석과 평가** , 그리고 **분석 목적과의 일치성**을 확인
  - 데이터마이닝을 통해 발견한 **지식을 업무에 활용** 하기 위한 방안 마련의 단계
  - 필요에 따라 데이터 선택 프로세스에서 데이터마이닝 프로세스를 반복 수행
  

## 3. CRISP-DM 분석 방법론

#### 가. 개요

- **CRISP-DM (Cross Industry Standard Process for Data Mining)**
  - 1996년 유럽연합의 ESPRIT에서 있었던 프로젝트에서 시작
  - **주요한 5개의 업체들** (Daimler-Chrysler, SPSS, NCR, Teradata, OHRA)이 주도
  - **계층적 프로세스 모델** 로써 4개 레벨로 구성

#### 나. CRISP-DM의 4레벨 구조

최상위

- **여러 개의 단계 (Phases)**
- **일반화 테스크 (Generic Tasks)**
- **세분화 테스크 (Specialized Tasks)**
- **프로세스 실행 (Process Instances)**

최하위

#### 다. CRISP-DM의 프로세스

- 총 6단계로 구성되어 있으며, 각 단계는 단방향으로 구성되어 있지 않고 **단계 간 피드백**을 통하여 단계별 완성도를 높이게 되어 있다

Business Understanding <=> Data Understanding -> Data Preparation <=> Modeling -> Evaluation -> Deployment  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ ㄴ-------------------------------------------------------------------------------------------------------------|

- **업무이해 (Business Understanding)**
  - 비즈니스 관점에서 프로젝트의 **목적과 요구사항을 이해** 하기 위한 단계
  - 도메인 지식을 **데이터 분석을 위한 문제정의** 로 변경하고 초기 프로젝트 계획을 수립하는 단계
  - **[수행업무]:** 업무 목적 파악, 상황 파악, 데이터 마이닝 목표 설정, 프로젝트 계획 수립
  
- **데이터 이해 (Data Understanding)**
  - 분석을 위한 **데이터를 수집** 하고 데이터 **속성을 이해** 하기 위한 단계
  - 데이터 품질에 대한 문제점을 식별하고 숨겨져 있는 **인사이트를 발견** 하는 단계
  - **[수행업무]:** 초기 데이터 수집, 데이터 기술 분석, 데이터 탐색, 데이터 품질 확인

- **데이터 준비 (Data Preparation)**
  - 분석을 위하여 수집된 데이터에서 분석기법에 적합한 데이터를 편성하는 단계 (많은 시간 소요 가능)
  - **[수행업무]:** 분석용 **데이터 셋 선택, 데이터 정제**, 분석용 데이터 셋 편성, 데이터 통합, 데이터 포맷팅
  
- **모델링 (Modeling)**
  - 다양한 **모델링 기법과 알고리즘을 선택** 하고 모델링 과정에서 사용되는 파라미터를 **최적화** 해 나가는 단계
  - 모델링 과정에서 데이터 셋이 추가로 필요한 경우 데이터 준비 단계를 반복 수행할 수 있음
  - 모델링 결과를 테스트용 데이터 셋으로 평가하여 모델의 **과적합(Over-fitting) 문제를 확인**
  - **[수행업무]:** 모델링 기법 선택, 모델 테스트 계획 설계, 모델 작성, **모델 평가**
  
- **평가 (Evaluation)**
  - 모델링 결과가 **프로젝트 목적에 부합하는지 평가**하는 단계
  - 데이터마이닝 결과를 최종적으로 수용 할 것인지 판단
  - **[수행업무]:** **분석결과 평가, 모델링 과정 평가, 모델 적용성 평가**
  
- **전개 (Deployment)**
  - 모델링과 평과 단계를 통하여 완성된 모델을 **실 업무에 적용** 하기 위한 계획을 수립하는 단계
  - 모니터링과 모델의 **유지보수 계획** 마련
  - CRISP-DM의 마지막 단계, 프로젝트 종료 관련 프로세스를 수항하여 프로젝트 마무리
  - **[수행업무]:** 전개 계획 수립, 모니터링과 유지보수 계획 수립, 프로젝트 종료보고서 작성, 프로젝트 리뷰

**예상문제**  
**24. KDD분석 방법론에서 잡음, 이상치, 결측치를 식별하여 분석용 데이터셋을 선택하고 분석에 필요한 변수 등을 선정하는 단계와 유사한 CRISP-DM 방법 방법론의 단계는?**  

(정답): 데이터 준비

**25. 다음 중 CRISP-DM 방법론의 모델링 단계에서 수행하는 테스크(Task)로 적절하지 않은 것은 무엇인가?**

1. 모델 테스트 계획 설계
2. 모델 평가
3. 모델링 기법 선택
4. 모델 적용성 평가

(정답): 4

## 4. KDD와 CRISP-DM의 비교

**KDD** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  **CRISP-DM**

- 분석대상 비즈니스 이해 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **업무 이해 (Business Understanding)**
- **데이터셋 선택 (Data Selection)** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **데이터의 이해 (Data Understanding)**
- **데이터 전처리 (Pre-processing)**
- **데이터 변환 (Transformation)** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **데이터 준비 (Data Preparation)**
- **데이터 마이닝 (Data Mining)** \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **모델링 (Modeling)**
- **데이터 마이닝 결과 평가 (Interpretation/Evaluation)** \ \ \ \ \ \ \ **평가 (Evaluation)**
- 데이터 마이닝 활용 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **전개 (Deployment)**


