---
title: "Part 2: Data Analysis Master Plan"
output: rmarkdown::github_document
---

# Table of Contents

- **Chapter 1 - 마스터 플랜 수립 프레임 워크 (Framework for Establishing a Master Plan)**
  - 분석 마스터 플랜 수립 프레임 워크
  
- **Chapter 2 - 분석 거버넌스 체계 수립 (Establishing an Analysis Governance System)**
  - 거버넌스 체계
  - 데이터 분석 수준진단
  - 분석지원 인프라 방안 수립
  - 데이터 거버넌스 체계 수립
  - 데이터 조직 및 인력방안 수립
  - 분석 과제 관리 프로세스 수립
  - 분석 교육 및 변화관리
  
  
# Chapter 1 - 마스터 플랜 수립 프레임 워크 (Framework for Establishing a Master Plan)

## 1. 분석 마스터 플랜 수립 프레임 워크

#### 가. 마스터 플랜 수립 개요

- 분석 마스터플랜은 일반적인 ISP(Information Strategy Planning) 방법론을 활용하되 데이터 분석 기획의 특성을 고려하여 수행하고 기업에서 필요한 데이터 분석 과제를 빠짐없이 도출한 후 과제의 우선순위를 결정하고 단기 및 중/장기로 나누어 계획을 수립
- **우선순위 고려 요소**
  - 전략적 중요도
  - 비즈니스 성과/ROI
  - 실행 용이성
- **적용 범위/방식 고려 요소**
  - 업무 내재화 적용 수준
  - 분석 데이터 적용 수준
  - 기술 적용 수준

#### 나. 수행 과제 도출 및 우선순위 평가

- **우선순위 평가 방법 및 절차**
  - 정의된 데이터 과제에 대한 실행 순서를 정하는 것을 의미
  - 업무별 도출된 분석과제를 우선순위 평가 기준에 따라 평가한 뒤, 
  - 과제 수행의 선/후행 관계를 고려하여 적용순위를 조정해 최종 확정
  - <절차>
    - **분석 과제 도출**
    - **우선순위 평가** 
      - 과제우선순위 기준 수립
    - **우선순위 정련**
      - 분석 과제 수행의 선후 관계 분석을 통해 순위조정

- **일반적인 IT프로젝트의 우선순위 평가 예시**
  - 정보전략계획(ISP)과 같은 일반적인 IT프로젝트 과제의 우선순위 평가를 위해 전략적 중요도, 실행 용이성 등 기업에서 고려하는 중요 가치기준에 따라 다양한 관점에서의 우선순위 기준을 수립하여 평가한다
  - <예시>
  - **[1] 전략적 중요도**
    - 전략적 필요성
    - 시급성
  - **[2] 실행 용이성**
    - 투자 용이성
    - 기술 용이성
  
- **ROI 관점에서 빅데이터의 핵심 특징**
  - 투자비용 요소 (Investment)
    - **Volume (3V):** 데이터 규모/양
    - **Variety (3V):** 데이터 종류/유형
    - **Velocity (3V):** 데이터 생성속도/처리속도
  - "+"
  - 비즈니스 효과 (Return)
    - **Value (4V):** 분석 결과 활용 및 실행을 통한 비즈니스 가치

- **데이터 분석과제 추진시 고려해야 하는 우선순위 평가 기준**
  - <과제 우선순위 평가 기준>
  - **시급성** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ <- **비즈니스 효과 (Return)** Value
    - 전략적 중요도
    - 목표가치 (KPI)
  - **난이도** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ <- **투자비용 요소 (Investment)** Volume, Variety, Velocity
    - 데이터 획득/저장/가공 비용
    - 분석 적용 비용
    - 분석 수준

- **포트폴리오 사분면 분석을 통한 과제 우선순위를 선정하는 기법**
  - <분석 과제 우선순위 선정 매트릭스>
  
난이도 \ \ \ \ \ **Difficult** \ \ \ \ \ \ \ \ I \ \ \ \ \ \ \ \ \ \ \ \ II  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **Easy** \ \ \ \ \ \ \ \ \ \ \ \ III \ \ \ \ \ \ \ \ \ \ IV  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **현재** \ \ \ \ \ \ **미래**   
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 시급성
  
  - **I 사분면**
    - 전략적 중요도가 높아 경영에 미치는 영향이 크므로 현재 시급하게 추진이 필요함
    - 난이도가 높아 현재 수준에서 과제를 바로 적용하기에 어려움
  - **II 사분면**
    - 현재 시점에서는 전략적 중요도가 높지 않지만 중장기적 관점에서는 반드시 추진되어야 함
    - 분석 과제를 바로 적용하기에는 난이도가 높음
  - **III 사분면**
    - 전략적 중요도가 높아 현재 시점에 전략적 가치를 두고 있음
    - 과제 추진의 난이도가 어렵지 않아 우선적으로 바로 적용 가능할 필요성이 있음
  - **IV 사분면**
    - 전략적 중요도가 높지 않아 중장기적 관점에서 과제 추진이 바람직함
    - 과제를 바로 적용하는 것은 어렵지 않음
  
  - <분석 과제 우선순위 조정>
    - 우선 순위를 **시급성**에 둔다면
      - III -> IV -> II 영역 순
    - 우선 순위를 **난이도**에 둔다면
      - III -> I -> II 영역 순
  - 데이터 양, 특성, 분석 범위 등에 따라 우선순위 조정 가능
  - 기술적 요소에 따라 우선순위 조정 가능
  - 분석 범위에 따라 우선순위 조정 가능
  

#### 다. 이행계획 수립

- **로드맵 수립**
  - 분석 과제에 대한 포트폴리오 사분면(Quadrant) 분석을 통해 과제의 1차적 우선순위를 결정한다
  - 분석 과제별 적용범위 및 방식을 고려하여 최종적인 실행 우선순위를 결정한 후 단계적 구현 로드맵을 수립니다
  - 단계별로 추진하고자 하는 목표를 정의한다
  - 추진 과제별 선/후행 관계를 고려하여 단계별 추진 내용을 정렬한다

- **세부 이행계획 수립**
  - 데이터 분석체계는 고전적인 폭포수(Water-Fall) 방식도 있으나 반복적인 정련과정을 통하여 프로젝트의 완성도를 높이는 방식을 주로 사용한다
  - 반복적인 분석 체계는 모든 단계를 반복하기보다 데이터 수집 및 확보와 분석데이터를 준비하는 단계를 순차적으로 진행하고, 모델링 단계는 반복적으로 수행하는 혼합형을 많이 적용하며, 이러한 특성을 고려하여 세부적인 일정계획도 수립해야 한다

**기출 문제**  
**36. 분석 마스터 플랜에 대한 설명으로 가장 부적절한 것은?**  

1. 분석 마스터 플랜은 중장기 마스터 플랜 수립과제 도출 및 우선순위 평가, 과제별 이행계획 수립 순으로 진행된다  
2. 분석 과제 로드맵은 과제의 우선순위를 고려하여 작성하되 과제별 선후관계를 감안하여 반복적이고 순환적인 계획을 작성한다  
3. 과제 우선순위 평가는 비즈니스 효과인 시급성과 투자비용 요소인 난이도에 근거하여 결정된다  
4. 과제별 데이터 분석 체계는 폭포수 방식도 있으나 반복적인 정련과정을 통하여 과제의 완성도를 높이는 방식으로 많이 사용한다.  

(정답): 1번  
(해설): 분석 마스터 플랜을 일반적인 ISP 방법론을 활용하되 데이터 분석 기획의 특성을 고려하여 수행하고 기업에서 필요한 **데이터분석 과제를 빠짐없이 도출한 후 과제의 우선 순위를 결정하고 단기 및 중/장기로 나누어 계획을 수립한다**

**37. 분석 마스터 플랜 수립에서 과제 우선순위 결정과 관련한 내용으로 부적절한 것은?**

1. 가치는 투자비용 요소이다  
2. 전략적 중요도, ROI, 실행 용이성은 분석과제 우선순위 결정에 고려할 사항이다  
3. 시급성과 전략적 필요성은 전략적 중요도의 평가 요소이다  
4. 적용 기술의 안전성 검증은 기술 용이성의 평가 요소이다  

(정답): 1번  
(해설): 가치는 투자비용 요소가 아닌 비즈니스 효과 측면에 포함되어 있다

**38. 다음 중 빅데이터 특징 4V를 고려한 분석 ROI에서 비즈니스 효과에 해당하는 것은?**

1. Volume  
2. Variety  
3. Velocity  
4. Value

(정답): 4번   

**39. 다음 빅데이터의 특징 중 투자비용 요소 또는 난이도를 평가하는 요소가 아닌 것은?**

1. 크기 (Volume)  
2. 다양성 (Variety)  
3. 속도 (Velocity)  
4. 가치 (Value)  

(정답): 4번

**40. 다음 중 분석 중 마스터플랜의 세부 이행계획 수립 시 고려해야 할 데이터 분석 체계(분석방법론)에 대한 설명으로 가장 적절한 것은?**  

1. 데이터 분석 체계는 이해도가 높은 폭포수 모델이 가장 적정하다  
2. 반복적 정련 방식은 데이터 수집 및 확보 단계를 반복적으로 수행한다  
3. 프로토타입(Prototpye) 모델은 데이터 분석체계로는 적절하지 못하다  
4. 프로젝트의 세부 일정계획도 데이터 분석체계를 고려하여 작성한다  

(정답): 4번  
(해설): 2번은, 데이터 수집 및 확보 단계는 **순차적**으로 한번만 진행한다. 그 다음 단계(Modeling)부터는 반복적으로 수행한다


# Chapter 2 - 분석 거버넌스 체계 수립 (Establishing an Analysis Governance System)

## 1. 거버넌스 체계

#### 가. 개요

- 기업에서 데이터를 이용한 의사결정이 강조될수록 데이터 분석과 활용을 위한 체계적인 관리가 중요해진다
- 조직 내 분석 관리체계를 수립해야 하는 이유는 데이터 분석을 기업의 문화로 장착하고 데이터 분석업무를 지속적으로 고도화하기 위해서이다

#### 나. 구성요소
- 마스터 플랜 수립 시점에서 데이터 분석의 지속적인 적용과 확산을 위한 거버넌스 체계는 다음으로 구성된다
- **분석 기획 및 관리 수행 조직 (Organization)**
- **과제 기획 및 운영 프로세스 (Process)**
- **분석 관련 시스템 (System)**
- **데이터 (Data)**
- **분석 관련 교육 및 마인드 육성 체계 (Human Resources)**

## 2. 데이터 분석 수준진단

#### 가. 개요

- 기업들은 데이터 분석의 도입 여부와 활용에 명확한 분석 수준을 점검할 필요가 있다
- 데이터분석의 수준진단을 통해 데이터 분석 기반을 구현하기 위해서는 무엇을 준비하고 보완해야 하는지 등 분석의 유형 및 분석의 방향성을 결정할 수 있다
- 데이터 분석 수준 진단을 위한 **분석 준비도(Readiness)**와 **분석 성숙도(Maturity)**의 구성은 아래와 같다
- **분석 준비도 (Readiness)**
  - 분석 업무
  - 분석 인력, 조직
  - 분석 기법
  - 분석 데이터
  - 분석 문화
  - 분석 인프라
- **분석 성숙도 (Maturity)**
  - 도입 (비즈니스, 조직 및 역량, IT)
  - 활용 (비즈니스, 조직 및 역량, IT)
  - 확산 (비즈니스, 조직 및 역량, IT)
  - 최적화 (비즈니스, 조직 및 역량, IT)

#### 나. 수준 진단 목표 2가지

- **정의**
  - 기업의 현재 분석 수준을 명확히 이해하고, 수준진단 결과를 토대로 미래의 목표수준을 정의한다
  - 데이터 분석을 위한 기반 또는 환경이 유사업종 또는 타 경쟁사에 비해 어느 정도 수준이고
  - 데이터를 활용한 분석의 경쟁력 확보를 위해 어떠한 영역에 선택과 집중을 해야 하는지
  - 어떤 관점을 보완해야 하는지 등 개선방안을 도출한다

- **분석 준비도 (Readiness)**
  - **목표**
    - 기업의 데이터 분석 도입의 수눚을 파악하기 위한 진단방법
  - **구성**
    - 총 6가지 (분석업무 파악, 인력 및 조직, 분석 기법, 분석 데이터, 분석 문화, IT 인프라)
  - **진단 과정**
    - 영역별로 세부 항목에 대한 수준 파악
    - 진단결과 전체 요건 중 일정 수준이상 충족하면 분석업무 도입
    - 충족하지 못할 시 분석 환경 조성
  - **데이터 분석 준비도 프레임 워크**
    - 분석업무 파악 \ \ \ \ \ \ \ **<span style="color: red;">빈도 높음!</span>**
      - 발생한 사실 분석 업무
      - 예측분석 업무
      - 시뮬레이션 분석 업무
      - 최적화 분석 업무
      - 분석 업무 정기적 개선
    - 인력 및 조직
      - 분석 전문가 직무 존재
      - 분석 전문가 교육훈련 프로그램
      - 관리자들의 기본적 분석 능력
      - 전사 분석 업무 총괄 조직 존재
      - 경영진 분석 업무 이해 능력
    - 분석 기법
      - 업무별 적합한 분석 기법 사용
      - 분석 업무 도입 방법론
      - 분석 기법 라이브러리
      - 분석 기법 효과성 평가
      - 분석 기법 정기적 개선
    - 분석 데이터 \ \ \ \ \ \ \ **<span style="color: red;">빈도 높음!</span>**
      - 분석업무를 위한 데이터 충분성
      - 분석업무를 위한 데이터 신뢰성
      - 분석업무를 위한 데이터 적시성
      - 비구조적 데이터 관리
      - 외부 데이터 활용 체계
      - 기준데이터 관리(MDM)
    - 분석 문화
      - 사실에 근거한 의사결정
      - 관리자의 데이터 중시
      - 회의 등에서 데이터 활용
      - 경영진의 직관보다 데이터
      - 데이터 공유 및 현업 문화
    - IT 인프라
      - 운영시스템 데이터 통합
      - EAL ETL 등 데이터 유통체계
      - 분석 전용 서버 및 스토리지
      - 빅데이터 분석 환경
      - 통계 분석 환경
      - 비주얼 분석 환경

- **분석 성숙도 모델 (Maturity)**
  - **조직의 성숙도 평가 도구**
    - CMMI (Capability Maturity Model Integration) 모델
  - **성숙도 수준분류**
    - 도입단계, 활용단계, 확산단계, 최적화단계
  - **분석 성숙도 진단 분류**
    - 비즈니스 부문, 조직/역량 부문, IT 부문  
  - <분석 성숙도 모델 CMMI>
  - **설명**
    - **도입단계**
      - 분석을 시작하여 환경과 시스템을 구축
    - **활용단계** \ \ \ \ \ \ \ **<span style="color: red;">빈도 높음!</span>**
      - 분석 결과를 실제 업무에 적용
    - **확산단계** \ \ \ \ \ \ \ **<span style="color: red;">빈도 높음!</span>**
      - 전사 차원에서 분석을 관리하고 공유
    - **최적화단계**
      - 분석을 진화시켜서 혁신 및 성과 향상에 기여
  - **비즈니스 부문**
    - **도입 단계**
      - 실질분석 및 통계
      - 정기보고 수행
      - 운영 데이터 기반
    - **활용 단계**
      - 미래 결과 예측
      - **시뮬레이션**
      - 운영 데이터기반
    - **확산 단계**
      - 전사성과 실시간분석
      - 프로세스혁신 3.0
      - 분석규칙관리
      - 이벤트 관리
    - **최적화 단계**
      - 외부환경 분석 활용
      - **최적화 업무 적용**
      - 실시간 분석
      - 비즈니스 모델 진화
  - **조직/역량 부문**
    - **도입 단계**
      - 일부 부서에서 수행
      - 담당자 역량에 의존
    - **활용 단계**
      - 전문 담당부서에서 수행
      - 분석 기법 도입
      - 관리자가 분석 수행
    - **확산 단계**
      - **전사모든부서 수행**
      - 분석 COE 조직 운영
      - **데이터 사이언티스트 확보**
    - **최적화 단계**
      - **데이터 사이언스 그룹**
      - 경영진 분석 활용
      - 전략 연계
  - **IT 부문**
    - **도입 단계**
      - 데이터 웨어하우스
      - 데이터 마트
      - ETL/EAI
      - OLAP
    - **활용 단계**
      - 실시간 대시보드
      - 통계분석 환경
    - **확산 단계**
      - 빅데이터관리 환경
      - **시뮬레이션/최적화**
      - 비주얼 분석
      - 분석 전용 서버
    - **최적화 단계**
      - 분석 협업 환경
      - 분석 Sandbox
      - **프로세스 내재화**
      - 빅데이터 분석

- **분석 수준 진단 결과**
  - 기업의 현재 분석 수준을 객관적으로 파악
  - 경쟁사의 분석 수준과 비교하여 분석 경쟁력 확보 및 강화를 위한 목표 수준 설정 가능
  - **분석 관점에서의 사분면 분석 (Analysis Quadrant)**
    - 사분면 분석 같이 분석 관점에서 **4가지 유형으로** 분석 주준 진단 결과를 구분하여 향후 고려해야 하는 데이터 분석 수준에 대한 목표 방향을 정의하고, 유형별 특성에 따라 개선방안을 수립

\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 높음  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 준비도는 낮으나 조직, 인력, 분석 \ \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 기업에 필요한 6가지 분석 구성요  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 업무, 분석기법 등을 기업 내부에서 \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 소를 갖추고 있고, 현재 부분적으로  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 제한적으로 사용하고 있어 1차적으 \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 도입되어 지속적인 확산이 필요한  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 로 정착이 필요한 기업 \ \ \ \ \ **정착형** \ \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ **확산형** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 기업  
**준비도** 낮음 ------------------------------------------------------------------------------------------------------ 높음  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **준비형** \ \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ **도입형**   
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 기업에 필요한 데이터, 인력, 조직, \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 기업에서 활용하는 분석업무, 기법  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 분석업무, 분석기법 등이 적용되어 \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 등은 부족하지만 적용조직 등 준비  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 있지 않아 사전준비가 필요한 기업 \ \ \ \ \ \ \ \ | \ \ \ \ \ \ \ \ 도가 높아 바로 도입할 수 있는 기업   
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 낮음  
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ **성숙도**  


**기출 문제**  
**41. 다음 중 분석 거버넌스 체계 구성요소로 보기 어려운 것은?**  
1. 과제 기획운영 프로세스  
2. 분석의 데이터 및 추진 조직  
3. 과제 예산 및 비용 집행  
4. IT 시스템 및 마인드 육성 체계  

(정답): 3번  

**42. 데이터 분석 기획을 위해서 데이터 분석 수준진단이 필요하다. 분석 준비도와 분석 성숙도를 통해 데이터 분석 수준을 진단하게 되는데, 분석준비도 6개의 영역 중 2가지를 적으시오.**

(정답): 분석 업무 파악, 분석 인력 및 조직, 분석 기법, 분석 데이터, 분석 문화, 분석 인프라

**44. 기업의 데이터 분석 도입 수준을 파악하기 위한 진단방법인 분석 준비도에서 분석 업무파악 항목으로 부적절한 것은?**  

1. 발생한 사실 분석 업무  
2. 예측분석 업무  
3. 분석업무 정기적 개선  
4. 분석 기법 라이브러리  

(정답): 4번  

**45-1. 다음 중 분석 성숙도 모델 중 기업에서 활용하는 분석 업무 및 분석 기법 등은 부족한 상태이지만, 조직 및 인력 등 준비도가 높은 유형으로 데이터 분석을 바로 도입할 수 있는 수준의 성숙단계는?**

1. 준비형  
2. 정착형  
3. 도입형  
4. 확산형  

(정답): 3번  

## 3. 분석지원 인프라 방안 수립

#### 가. 개요

- 분석과제 단위별로 별도의 분석시스템을 구축하는 경우, 관리의 복잡도 및 비용의 증대라는 부작용이 나타난다
- 따라서 분석마스터 플랜을 기획하는 단계에서부터 장기적이고 안정적으로 활용할 수 있는 확장성을 고려한 플랫폼 구조를 도입하는 것이 적절하다

#### 나. 플랫폼

- 응용프로그램이 실행될 수 있는 기초를 이루는 컴퓨터 시스템을 의미
- 하드웨어에 탑재되어 데이터 분석에 필요한 프로그래밍 환경과 실행 및 서비스 환경 제공
- 새로운 데이터 분석 니즈가 존재할 경우 개별적 분석 시스템을 추가하는 방식이 아닌 서비스를 추가적으로 제공하는 방식으로 확장성을 높일 수 있다

## 4. 데이터 거버넌스 체계 수립

#### 가. 데이터 거버넌스의 개요

- 전사 차원의 모든 데이터에 대하여 정책 및 지침, 표준화, 운영조직 및 책임 등의 표준화된 관리체계를 수립하고 운영을 위한 프레임워크(Framework) 및 저장소(Repository)를 구축하는 것을 의미
- 마스터 데이터(Master Data), 메타 데이터(Meta Data), 데이터 사전(Data Dictionary)은 데이터 거버넌스의 중요한 관리 대상

#### 나. 데이터 거버넌스 구성요소

- **원칙(Principle)**
  - 데이터를 유지/관리하기 위한 지침과 가이드
  - 보안, 품질 기준, 변경관리
- **조직(Organization)**
  - 데이터를 관리할 조직의 역할과 책임
  - 데이터 관리자, 데이터베이스 관리자, 데이터 아키텍트
- **프로세스(Process)**
  - 데이터 관리를 위한 활동과 체계
  - 작업 절차, 모니터링 활동, 측정 활동

#### 다. 데이터 거버넌스 체계

- **데이터 표준화**
  - 데이터 표준 용어 설정
  - 명명 규칙(Name Rule) 수립
  - 메타 데이터(Meta Data) 구축
  - 데이터 사전(Data Dictionary) 구축
- **데이터 관리 체계**
  - 메타 데이터(Meta Data)와 데이터 사전(Data Dictionary)의 관리 원칙 수립
- **데이터 저장소 (Repository) 관리**
  - 메타데이터 및 표준 데이터를 관리하기 위한 전사 차원의 장소를 구성
  - 저장소는 데이터 데이터 관리체계 지원을 위한 워크플로우(Workflow) 및 관리용 응용 소프트웨어(Application)를 지원하고 관리 대상 시스템과의 인터페이스를 통한 통제가 이루어져야 한다
  - 데이터 구조 변경에 따른 **사전 영향 평가** 도 수행되어야 효율적인 활용이 가능하다
- **표준화 활동**
  - 데이터 거버넌스 체계를 구축한 후 표준 준수 여부를 주기적으로 점검하고 모니터링

**기출문제**  
**46. 아래에서 설명하는 데이터 거버넌스 체계 항목은 무엇인가?**  
<아래>  데이터 표준 용어 설정, 명명 규칙 수립, 메타 데이터 구축, 데이터 사전 구축 등의 업무로 구성된 데이터 거버넌스 체계  

1. 데이터 표준화  
2. 데이터 관리 체계  
3. 데이터 저장소 관리  
4. 표준화 활동  

(정답): 1번  


## 5. 데이터 조직 및 인력방안 수립

#### 가. 현황

- 데이터를 효과적으로 분석/활용하기 위해 기획, 운영 및 관리를 전담할 수 있는 전문 분석조직 필요성이 제기됨

#### 나. 분석 조직의 개요

- **목표**
  - 기업 경쟁력 확보를 위하여 비즈니스 질문(Question)과 이에 부합하는 가치(Value)를 찾고 비즈니스를 최적화(Optimization)하는 것
- **역할**
  - 전자 및 부서의 분석 업무를 발굴하고 전문적 기법과 분석 도구를 활용하여 기업 내 존재하는 빅데이터 속에서 Insight를 전파하고 이를 Action화 하는 것
- **구성**
  - 기초통계학 및 분석 방법에 대한 지식과 분석 경험을 가지고 있는 인력으로 전사 또는 부서 내 조직으로 구성하여 운영

#### 다. 조직 및 인력 구성 시 고려사항

- **주요 고려사항**
  - **조직구조**
    - 비즈니스 질문(Question)을 선제적으로 찾아 낼 수 있는 구조인가?
    - 분석 전담조직과 타 부서관 유기적인 협조와 지원이 원활한 구조인가?
    - 효율적인 분석 업무를 수행하기 위해 분석 조직의 내부 조직구조는?
    - 전사 및 단위부서가 필요 시 접촉하며 지원할 수 있는 구조인가?
    - 어떤 형태의 조직(중앙지비중형, 분산형)으로 구성하는 것이 효율적인가?
  - **인력구성**
    - 비즈니스 및 IT 전문가의 조합으로 구성되어야 하는가?
    - 어떤 경험과 어떤 스킬을 갖춘 사람으로 구성해야 하는가?
    - 통계적 기법 및 분석 모델링 전문 인력을 별도로 구성해야 하는가?
    - 전사 비즈니스를 커버하는 인력이 없다. 그렇다면?
    - 전사 분석업무에 대한 적합한 인력 규모는 어느 정도인가?
- **분석을 위한 3가지 조직 구조** \ \ \ \ \ \ \ \ \ \ **<span style="color: red;">빈도 높음!</span>**
  - **집중구조**
    - 전사 분석업무를 별도의 분석전담 조직에서 담당
    - 전략적 중요도에 따라 분석조직이 우선순위를 정해서 진행 가능
    - 현업 업무부서의 분석업무와 이중화/이원화 가능성 높음
  - **기능구조**
    - 일반적인 분석 수행 구조
    - 별도 분석조직이 없고 해당 업무 부서에서 분석 수행
    - 전사적 핵심분석이 어려우며, 부서 현황 및 실적 통계 등 과거 실적에 국한된 분석 수행 가능성 높음
  - **분산구조**
    - 분석조직 인력들을 현업부서로 직접 배치하여 분석업무 수행
    - 전사차원의 우선순위 수행
    - 분석결과에 따른 신속한 Action 가능
    - 베스트 프랙티스 공유 가능
    - 부서 분석업무와 역할 분담 명확히 해야함 (-> 업무과다 이원화 가능성)
    
- **분석조직의 인력구성**
  - **분석 조직(DSCoE, Data Science Center of Excellence)**
  - Director/Manager
    - 비즈니스 인력
    - IT기술 인력
    - 분석전문 인력
    - 변화관리 인력
    - 교육담당 인력
  
**기출문제**  
**47. 데이터 분석 조직 구조의 설명으로 가장 부적절한 것은?**

1. 집중형 조직 구조는 조직 내 별도의 분석 전담조직을 독립적으로 구성하는 것으로서 분석 업무의 중복 또는 이원화의 이슈가 있다  
2. 기능 중심의 조직 구조는 별도의 분석 전담 조직을 구성하지 않고 해당 부처에서 직접 분석을 수행함으로써 국한된 분석 수행 이슈가 존재한다  
3. 분산구조는 분석 조직의 인력을 현업부서에 배치하여 분석 업무를 수행함으로써 분석이 집중되지 못해 신속한 실무적용이 어렵다  
4. 분석조직은 분석 전문 인력뿐만 아니라 도메인 전문가, IT인력, 변화관리 및 교육담당인력으로 구성되어야 효율적인 운영이 가능하다  

(정답): 3번


## 6. 분석 과제 관리 프로세스 수립

#### 가. 현황

- 분석 마스터 플랜이 수립되고 초기 데이터 분석 과제가 성공적으로 수행되는 경우, 지속적인 분석니즈 및 기회가 분석 과제 형태로 도출될 수 있다
- 이런 과정에서 분석 조직이 수행할 주요한 역할중의 하나가 분석 과제의 기획 및 운영이므로 이를 체계적으로 관리하기 위한 프로세스를 수립해야 한다

#### 나. 과제 관리 프로세스

- **과제 발굴**
  - [1] 분석 Idea 발굴
  - [2] 분석과제 후보제안 (과제후보 pool)
  - [3] 분석과제 확정 (전사분석 조직)
- **과제 수행**
  - [4] 팀구성
  - [5] 분석과제 실행 (전사분석 조직의 과제 수행 지원)
  - [6] 분석과제 진행관리 (전사분석 조직)
  - [7] 결과 공유/개선 (과제결과 pool)
  
**기출문제**  
**48. 다음 중 분석과제 관리 프로세스에 대한 설명으로 가장 부적절한 것은?**

1. 과제 발굴 단계에서는 분석 아이디어 발굴, 분석과제 후보제안, 분석과제 확정 프로세스가 있다  
2. 분석과제로 확정된 분석과제를 풀(pool)로 관리한다  
3. 분석과제 중에 발생된 시사점과 분석 결과물은 풀(pool)로 관리하고 공유된다  
4. 과제 수행 단계에서는 팀 구성, 분석과제 실행, 분석과제 진행관리, 결과 공유 프로레스가 있다  

(정답): 2번  
(해설): 분석과제 후보제안도 pool에 포함

## 7. 분석 교육 및 변화관리

#### 가. 개요

- 빅데이터의 등장으로 많은 비즈니스 영역에서 변화를 가져 왔다
- 이러한 변화에 보다 적극적으로 대응하기 위해서는 기업에 맞는 적합한 분석 업무를 도출하고, 가치를 높여줄 수 있도록 분석 조직 및 인력에 대한 지속적인 교육과 훈련을 실시하여야 한다
- 또한 경영층이 사실 기반(Fact-Based) 의사결정을 할 수 있는 문화를 정착시키는 등 지속적인 변화관리를 계획하고 수행하여야 한다
- 새로운 체계의 도입시에는 저항 및 기존 행태로 되돌아가는 관성이 존재하기 때문에 분석의 가치를 극대화하고 내재화하는 안정적인 추진기로 접어들기 위해서는 분석에 관련된 교육 및 마인드 육성을 위한 적극적인 변화 관리가 필요하다

#### 나. 분석 교육의 목표
- 단순한 툴 교육이 아닌 분석역량을 확보하고 강화하는 것에 추점을 맞추어 진행되어야 한다
- 분석적인 사고를 업무에 적용할 수 있도록 다양한 교육을 통해 조직 구성원 모두에게 분석기반의 업무를 정착시키고 이를 통해 데이터를 바라보는 관점, 데이터 분석과 활용 등이 기업 문화로 자연스럽게 확대되어야 한다