---
title: "Appendix"
output: rmarkdown::github_document
---

# 예상문제 1

#### 4. 다음 중 성공적인 분석을 위해서 고려해야 할 요소로 가장 부적절한 것은?

1. 관련 데이터의 파악  
2. **원점에서 솔루션 탐색**  
3. 비즈니스 케이스 확보  
4. 이행 저해 요소 관리

#### 5. 다양한 데이터 유형 중 정형 데이터 - 반정형 데이터 - 비정형 데이터 순서로 가장 적절한 것은?

1. **Demand Forecasts - Competitor pricing - Email records**  
2. Faceboom status - Weather data - Web logs  
3. RFID - Internet of things sensing - Loyalty program  
4. CRM Transcation data - Twitter density - Mobile location

#### 7. 다음 중 CRISP-DM 방법론의 모델링 단계에서 수행하는 테스크(task)로 적절하지 않은 것은?

1. 모델 테스트 계획 설계  
2. 모델 평가  
3. 모델링 기법 선택  
4. **모델 적용성 평가**  

#### 11. 비즈니스 모델 캔버스의 채널(Channels)에 대한 기능으로 가장 부적절한 것은?

1. 해당고객에게 접근하는 유통 채널을 공급한다  
2. 고객에게 밸류 프로포지션을 전달한다  
3. **구객 고객에 대한 에프터서비스를(A/S)를 제공하다**  
4. 기업이 제공하는 상품이나 서비스에 대한 고객의 이해를 높여준다  

#### 17. 다음 중 분석 프로젝트 관리에 대한 설명으로 가장 부적절한 것은?  

1. 데이터 분석 모델의 품질을 평가하기 위해 SPICE를 활용할 수 있다  
2. 분석 프로젝트 관리는 KSA ISO 21500:2013를 가이드로 활용할 수 있다  
3. **분석 프로젝트의 일정계획 수립시 데이터 수집에 대한 철저한 통제와 관리가 필요하다**  
4. 분석 프로젝트의 최종 산출물이 보고서인지 또는 시스템인지에 따라 프로젝트 관리에 차이가 있다.  

#### 19. 다음 중 데이터 분석을 위한 수준진단에서 '분석 준비도'의 분석 데이터 진단 항목으로 가장 부적절한 것은?  

1. 분석 업무를 위한 데이터 충실성, 신뢰성, 적시성  
2. **내부데이터 집중 활용 체계**  
3. 기준데이터 관리(MDM)  
4. 비구조적 데이터 관리  

#### 30. 빅데이터를 활용한 비즈니스는 기업에 많은 변화를 가져오고 있다. 다음 중 기업에서 이러한 변화를 수용하기 위한 중장기적 대응 방안으로 가장 거리가 먼 것은?

1. 분석 조직 및 인력에 대한 교육과 훈련  
2. 데이터 기반의 의사결정문화 정착  
3. **데이터 분석 도구 기반의 교육**  
4. 분석역량 강화를 위한 체계적인 계획 및 시행  

#### 32. 다음 중 기존에 행해졌던 데이터 분석과 비교한 빅데이터 분석의 특징으로 적절한 것은?

(ㄱ) 분석대상 데이터를 모든 형태 및 내외부 데이터로 확대한다  
(ㄴ) 데이터의 생산 기점에서부터 실시간에 가까운 분석이 가능하다  
(ㄷ) 데이터 마트에 정형 데이터를 적재하고 데이터 분석을 통하여 모델을 만들 수 있다  
(ㄷ) 고급 분석기법을 활용할 수 있다  

1. **(ㄱ), (ㄴ), (ㄷ)**  
2. (ㄱ), (ㄴ), (ㄹ)  
3. (ㄴ), (ㄷ), (ㄹ)  
4. (ㄱ), (ㄴ), (ㄷ), (ㄹ)  

해설: 고급 분석기법은 기존에도 사용되어 왔다

#### 33. 다음 중 빅데이터 분석에서 Self Service Analytics에 대한 설명으로 가장 부적절한 것은?  

1. Self Service Analytics에 포함되어야 하는 주요 기능은 BI도구, Ad hoc Report, OLAP, Visual Discovery, Machine Learning 등이다  
2. Self Service Analytics의 성공적인 적용을 위해서는 Reference Method의 작성 및 공유, 표준 데이터의 활용, 데이터 거버넌스, 도구 사용에 대한 지속적인 교육이 필요하다  
3. Self Service Analytics를 수행하기 위해서는 R, Python 등의 데이터 분석 언어와 많은 통계적 지식을 필요로 한다  
4. **Self Service Analytics는 상업용뿐만 아니라 OSS(Open Service Software)로도 구현되고, 분석의 성능 향상을 위하여 분산처리도 지원하고 있다**  

해설: Self Service Analytics에서는 분산처리를 지원하지 않는다

#### 34. 4차 산업혁명은 기존 산업을 초월하는 Mass Production, Mass Customization, Servitization을 구현하게 되는데, 다음 중 Servitization에 대한 설명으로 가장 부적절한 것은?

1. Service Science의 하나로 제품과 서비스의 결합을 통한 기업의 새로운 비즈니스 모델  
2. 제품의 서비스화와 서비스의 상품화를 모두 포함하는 결합 비즈니스 모델  
3. 파이프 라인 비즈니스를 넘어 플랫폼 비즈니스를 위한 모델  
4. **생산된 제품으이 특화를 통한 경쟁우위 확보 모델**  

#### 35. 다음 중 아래의 데이터 거버넌스 체계가 설명하는 항목은?  
<아래> 메타데이터 관리, 데이터 사전관리, 데이터 생명주기 관리

1. 데이터 표준화  
2. **데이터 관리 체계**  
3. 데이터 저장소 관리  
4. 표준화 활동

#### 37. 아래 (가) 안에 들어갈 용어를 기입하시오.  
<아래> 분석 방법론의 "시스템 구현" 단계에서 시스템으로 구현된 모델은 검증(Verification & Validation)을 위하여 단위 테스트, 통합테스트, 시스템 테스트 등을 실시한다. 이 중 (가) 테스트는 품질관리 차원에서 진행함으로써 적용된 시스템의 개관성과 안정성을 확보한다.

**시스템**

#### 38. 아래 (가)에 들어갈 용어를 기입하시오.  
<아래> 데이터 거버넌스 체계에서 데이터 저장소 (Repository) 관리란 메타데이터 및 표준 데이터를 관리하기 위한 전사 차원의 저장소로 구성된다. 저장소는 데이터 관리 체계 지원을 위한 워크 플로우 및 관리용 응용소프트웨어를 지원하고 관리 대상 시스템과의 인터페이스를 통한 통제가 이루어져야 한다. 또한 데이터 구조 변경에 따른 (가)도 수행되어야 효율적인 활용이 가능하다.

**사전 영향 평가**

#### 39. 아래 (가) 안에 들어갈 용어를 기입하시오.
<아래> 문제 탐색을 통해서 식별된 비즈니스 문제를 변환하는 단계로써, 문제 탐색 단계가 무엇을 어떤 목적으로 수행해야 하는가에 대한 관점이었다면, (가) 단계는 이를 달성하기 위해서 필요한 데이터 및 기법(How)을 도출하기 위한 데이터 분석의 문제로의 변환을 수행해야 한다.

**문제 정의**

#### 40. 아래 (가) 안에 들어갈 용어를 기입하시오.
<아래> 분석 모델을 가동중인 운영시스템에 적용하기 위해서는 모델에 대한 상세한 "알고리즘 설명서" 작성이 필요하다. "알고리즘 설명서"는 "시스템 구현" 단계에서 중요한 입력 자료로 활용되므로 필요시 (가) 수준의 상세한 작성이 필요하다.

**의사 코드**

#### 41. 아래 (가) 안에 들어갈 용어를 기입하시오.
<아래> 분석과제 관리 프로세스는 크게 과제 발굴과 (가)으로 나누어진다. 조직이나 개인이 도출한 분석 아이디러를 발굴하고 이를 과제화하여 분석과제 풀(Pool)로 관리하면서 분석과제가 확ㄱ정되는 분석과제 실행, 분석과제 진행 관리, 분석과제 결과 공유/개선의 분석관계 관리 프로세르를 수행하게 된다.

**과제 수행**

#### 42. 아래 (ㄱ), (ㄴ) 안에 들어갈 정확한 용어를 기입하시오.
<아래> 데이터 거버넌스 체계는 데이터 저장소(Repository)는 메타데이터 및 표준 데이터를 관리하기 위한 전사 차원의 저장소로 구성된다. 저장소는 데이터 관리 체계 지원을 위한 (ㄱ) 및 관리용 응용소프트웨어를 지원하고 관리 대상 시스템과의 인터페이스를 통한 통제가 이루어져야 한다. 또한 데이터 구조 변경에 따른 (ㄴ)도 수행되어야 효율적인 활용이 가능하다.

워크플로우, 사전영향평가

#### 43. 아래 (ㄱ), (ㄴ), (ㄷ) 안에 들어갈 융어를 순서대로 기입하시오.
<아래> 비즈니스 모델 캔버스는 9가지 블록을 단순화하여 (ㄱ), (ㄴ), 고객단위로 문제를 발굴하고ㅗ 이를 관리하는 규제와 감사, (ㄷ) 영역으로 나눠 분석 기회를 도출한다.

**업무, 제품, 지원 인프라**

#### 46. 문제가 주어지고 이에 대한 해법을 찾기 위하여 각 과정이 체계적으로 단계화되어 수행하는 분석과제 발굴 방식을 무엇이라 하는가?

**하양식 접근 방식**

#### 49. 소프트웨어와 시스템공학의 역량 숙성도를 측정하기 위한 모델로 소프트웨어 품질보중과 시스템 엔지니어링 분야의 품질보증 기술을 통합하여 개발된 평가모델로 1~5단계로 구성된 성숙도 모델은?

**능력 성숙도 통합 모델**

#### 50. 아래 () 안에 공통적으로 들어갈 용어는?
<아래> 기업 및 공공기관에서는 시스템의 중장기 로드맵을 정의하기 위한 ( )을(를) 수행한다. ( )은(는) 정보기술 또는 정보시스템을 전략적으로 활용하기 위하여 조직 내/외부 환경을 분석하여 기회나 문제점을 도출하고 사용자의 요구사항을 분석하여 시스템 구축 우선순위를 결정하는 등 중장기 마스터플랜을 수립하는 절차이다.

**ISP (Information, Strategy, Planning)**



# 예상문제 2

#### 8. 기업의 분석 기회 사례(Analytic Use Case)를 찾는 방법으로 부적절한 것은?

1. 기업의 비즈니스 모델 분석을 통해 경쟁력 강화를 위한 핵심 분석 기회를 식별한다  
2. 산업별, 업무 서비스별 분석 테마 후보군들의 벤치마킹 케이스를 통해 분석 기회를 식별한다  
3. **현재의 비즈니스 모델 및 유상, 동종 사례 탐색을 빠짐없이 도출한 분석 기회들을 구체적인 과제로 만든다**    
4. 특정 대상 프로세스를 감수한 후 업무 주제별로 분석 요건을 식별한다.

(해설): 3번이 비효율적이므로 분석기회사례를 활용한다

#### 12. 분석 프로젝트 수행 시 "전문성이 요구되는 데이터 분석 결과를 모든 프로젝트 이해 관계자가 공유할 수 있도록 해야 함"이라는 관리 포인트에 대한 부분 영역은?

1. 이해관계자(Stakeholder)  
2. 범위 (Scope)  
3. 품질 (Quality)  
4. **의사소통 (Communication)**  

#### 13. 분석 프로젝트 방법론 중 애자일과 폭포수 모델 비교 중 적절하기 않은 것은?

1. 애자일은 개발자와 사용자가 개발 초기부터 지속적으로 진행 상황을 공유하며 함께 진행한다  
2. 폭포수 모델은 단계별 산출물을 중요시하기 때문에 단계별 산출물에 대한 결과로 개발의 상황을 점검한다  
3. **애자일은 한번 결정된 단계는 그 이후에 변동이 적어햐 한다**  
4. **폭포수 모델은 계속적인 추가 요구 사항을 전제로 하는 방식이라 시작 단계에서는 부족한 점이 많지만 점차 완성도가 높아진다.**

#### 14. 데이터 분석을 함에 있어서 가장 중요한 요소는 크게 세 가지로 구성된다. 다음 중 세가지 구성 요소에 해당하지 않는 것은?

1. 분석의 근간이 되는 데이터  
2. 분석을 수행하는 분석 모델  
3. 이를 활용하여 데이터 분석을 수행하고 결과를 전달하는 분석가  
4. **데이터 분석을 위한 IT 솔루션**  

#### 18. 다음 중 빅데이터 분석 절차 순서가 적절한 것은?

**1. 분석 기획 -> 데이터 준비 -> 데이터 분석 -> 시스템 구현 -> 평가 및 전개**

#### 23. 빅데이터의 80% 이상이 빙정형 데이터라는 특성을 감안한다면 빅데이터 품질관리의 특성이라고 할 수 없는 것은?

1. 이미 생성된 데이터에 대한 정비가 사실상 어렵다  
2. 개별 데이터에 대한 타당성 검증은 경우에 따라 불필요하다  
3. 개인정보 외 외부에 공개가 어려운 민감성 데이터는 용도를 명확히 해야 한다  
4. **반드시 모든 데이터의 품질을 보장하기 위한 기준이 있어야 한다**

#### 29. I 사분면에 있는 9번과 같은 분석 과제는 난이도를 조율함으로써 적용 우선순위를 조정할 수 있다. 이때 고려 사항에 해당되지 않은 것은?

1. 분석 데이터의 적용 수준  
2. 분석 과제 수행 범위  
3. 업무 내재화 범위  
4. **투자비용 요소**  

(해설): 4번째는 "기존 아기텍처에 영향도" 가 차지

#### 30. 다음 중 비즈니스 모델 분석의 상향식 접근방식에서 특정 업무 영역의 주제 지향적 분석 기회를 발굴하는 절차가 가장 적절한 것은?

**2. 프로세스 분류 -> 프로세스 흐름 분석 -> 분석 요건 식별 -> 분석 요건 정의**

#### 37. CRISP-DM에서 데이터 준비단계에 영향을 미치는 단계는?

1. 모델링  
2. 평가  
3. 적용  
4. 데이터 이해  

#### 39. CRISP-DM에서 데이터 이해에 해당하지 않는 것은?

1. 초기데이터 수집  
2. 데이터 탐색  
3. 데이터 품질 확인  
4. **데이터 포맷팅**  

#### 40. 빅데이터 분석 방법 중 모델 검증 단계의 입력자료가 아닌 것은?

1. 모델링 결과 보고서  
2. 모델 평가 보고서  
3. 검증용 데이터  
4. **평가용 데이터**

### 단답형

#### 1. 다음 보기는 어느 분석 성숙도 모델 단계인가?

전사 차원에서 분석을 관리하고 공유, 데이터 사이언티스트 확보, 분석 CoE 조직 운영, 비주얼 분석, 시뮬레이션 및 최적화

**확산 단계**

#### 2. 아래 내용에 해당하는 경영혁신 도구는?

기업의 상품이나 서비스가 주는 가치를 고객의 효용이라는 관점에서 비교 평가 할 수 있는 도구로서, 현재의 상품이나 서비스가 제공하지 못하는 가치를 찾아내고 새로운 전략방향을 설정할 수 있도록 도움을 주는 도구

**전략 캔버스**

#### 3. 아래 문장 빈칸에 공통적으로 들어갈 알맞은 용어는?

현재의 비즈니스 모델 및 유사/동종 사례 탐색을 토ㅗㅇ해 빠짐없이 도출한 분석 기회들을 구체적인 과제로 만들기에 앞서 ()로 표기하는 것이 필요하다. ()는 풀어야 할 문제에 대한 상세한 설명 및 해당 문제를 해결했을 때 발생하는 효과를 명시함으로써 향후 데이터 분석 문제로의 전환 미치 적합성 평가에 활용하도록 한다. 

**분석 유즈 케이스**

#### 4. 다음 빈칸에 적절한 용어는?

()방법론은 "폭포수형 모델"에 반대대는 개념으로 탄생한 방법론이다. 즉 폭포수 모델은 프로젝트 개발 계획을 정해두고 각각의 단계별로 개발을 진행하는 형태의 개발 방법론이다. 때문에 중간에 문제가 생긴다면 처음부터 다시 각각의 단계를 진행해야 한다.

**애자일**

#### 5. 아래의 정의들이 공통적으로 설명하고 있는 것은?

가. 기업을 어떻게 경영하느냐를 설명하는 이야기  
나. 하나의 조직이 가치를 어떻게 만돌고, 제공하며, 획득하는지에 대한 근본적 원리의 표현

**비즈니스 모델**

#### 7. 다음 중 빈칸에 알맞은 용어는?

분석 과제를 도출하기 위한 접근방식으로 과정이 체계적이고 단계적으로 수행되는 ()과 데이터를 기반으로 문제의 재정의 및 해결 방안을 탐색하고 이를 지속적으로 개선하는 ()이 있다.

**하향식 접근 방식, 상향식 접근 방식**

#### 9. 아래 보기는 무엇에 관한 설명인지 적절한 용어를 쓰시오.

전사 차원에서 식별된 다양한 분석 주제 또는 과제를 대상으로 적용의 우선순위를 선정하고, 이를 실행하기 위한 구체적인 일정 계획, 단계적 구현 로드맵, 소요 인력, 예산 등 실행 계획을 수립하는 과정이다.

**분석 마스터 플랜**

#### 11. 다음 보기는 빅데이터 분석 방법론 중 어떤 스텝 과정을 서술하고 있는지 적절한 단어를 고르시오

분석용 데이터셋에 대한 정합성 검토, 데이터 요약, 데이터 특성을 파악하고 모델링에 필요한 데이터를 편성한다. 데이터 시각화 과정도 이때에 수행될 수 있다. 또한 데이터 분포 확인, 변수 간 연관성 분석 등도 수행된다.

**탐색적 분석 (Exploratory Data Analysis)**

#### 13. 다음 보기에서 이것이 의마하는 적절한 용어를 쓰시오

이것은 전사 차원의 모든 데이터에 대하여 정책 및 지침, 표준화, 운영조직 및 책임 등의 표준화된 관리 체계를 수립하고 운영을 위한 프레임 워크 및 저장소를 구축하는 것을 말한다.

**데이터 거버넌스**

#### 14. 빅데이터 분석을 도입하기에 앞서 현재 기업의 분석 수준을 명확하게 파악하는 것이 중요하다. 분석 준비도 (Readiness)를 진단하는 6가지 영역은 무엇인가?

**분석업무, 분석인력 및 조직, 분석기법, 분석데이터, 분석문화, 분석인프라**

#### 16. 다음은 분석 프로젝트 영역별 주요 관리 항목 중 무엇에 관한 설명인가?

전문성이 요구되는 데이터 분석의 결과를 모든 프로젝트 이해관계자가 공유할 수 있도록 해야 함

**의사소통**

#### 17. CRISP-DM 데이터 마이닝 방법론은 단계(phase), 일반과제(generic task), 세부과제(specialized task), 프로세스실행(process instance)의 4가지 개념으로 표현되는 세 가지 과제(task)로 구성된 계층적 프로레스 모델이다. 다음의 설명 단계중 어떤거?

숫자 값의 정제, 범주 값의 정제 및 데이터 마이닝 문제 유형이 군집화인지 모델링 예측인지 같은 다양한 상황에서 이 과제를 각각 처리하는 방법

**세부과제(specialized task)**

#### 19. 다음 빈칸에 공통으로 들어갈 알맞은 용어는?

()는 향후 프로젝트 수행계획의 입력물로 사용하기 때문에 프로젝트를 수행하는 이해관계자가 프로젝트의 방향을 설정하고 성공여부를 판별할 수 있는 주요한 자료로서 명확하게 작성되어야 한다  
()를 통해 분석별로 필요한 소스 데이터, 분석 방법, 데이터 입수 및 분석 난이도, 분석 수행 주기, 분석결과에 대한 검증 오너쉽, 상세 분석 과정 등을 정의한다

**분석 과제 정의서**

#### 20. 분석 성숙도 진단은 3개 부문을 무엇이 있는가?

**비즈니스, 조직역량, IT 부문**

#### 21. 분석 성숙도 진단에 따라 도입단계, 활용단계, 확산단계, 최적화 단계로 구분해 볼 수 있다. IT부문 중 분석 Sandbox, 프로세스 내재화는 어느 단계에 속하는가?

**최적화 단계**

#### 22. 조직 내 새로운 역량을 만들고 확산하기 위한 전문가들의 조합으로 구성된 조직으로 분석 업무를 전사적으로 총괄하는 조직을 무엇이라 하는가?

**CoE (Center of Excellence)**

#### 23. 자주 변하지 않고 처리 운용에 기본 자료로 제공되는 자료의 집합으로 인사데이터에서 이름, 생념월일 등이 해달될 수 있는 데이터를 무엇이라 하는가?

**마스터 데이터**

#### 24. 데이터 거버넌스 구성요소 중 데이터 관리를 위한 활동과 체계 및 작업절차, 모니터링 활동 등에 해당되는 요소는 무엇인가?

**프로세스**

#### 25. 조직 역량 부문 분석 성숙도 수준 중 데이터 사이언티스트 확보는 어떤 단계의 내용인가?

**확산단계**

#### 26. 외부 참조모델 탐색 시 유사, 동종의 환경에서 기존에 수행한 분석 과제를 살펴보는 것도 주요한 시사점을 도출해 준다. 창의적인 아이디어를 생산하기 위한 학습 도구이자 회의 기법인 이것을 통해 Quick & Easy 방식으로 아이디어를 얻고 기업에 적용할 분석 테마 후보 목록을 빠르게 도출할 수 있다. 이것은 무엇인가?

**브레인 스토밍**