---
title: "Part 3: 가치창조를 위한 데이터 사이언스와 전략 인사이트 (Data Science for Value Creation and Strategic Insight)"
output: rmarkdown::github_document
---

# Table of Contents
- **Chapter 1 - 빅데이터 분석과 전략 인사이트 (Big Data Analytics and Strategic Insight)**
  - 빅데이터 열풍과 회의론
  - 빅데이터 회의론의 원인 및 진단
  - 빅데이터 분석, 'Big'이 핵심이 아니다
  - 전략적 통찰이 없는 분석의 함정
  - 일차원적인 분석 vs 전략도출 위한 가치기반 분석
    
- **Chapter 2 - 전략 인사이트 도출을 위한 필요 역량 (Competency Needed to Draw Strategic Insights)** 
  - 데이터 사이언스의 의미와 역할
  - 데이터 사이언스의 구성요소
  - 데이터 사이언티스트의 요구 역량
  - 데이터 사이언스: 과학과 인문의 교차로
  - 전략적 통찰력과 인문학의 부활
  
- **Chapter 3 - 빅데이터 그리고 데이터 사이언스의 미래 (The Future of Big Data and Data Science)**
  - 빅데이터의 시대
  - 빅데이터 회의론을 넘어 가치 패러다임의 변화
  - 데이터 사이언스의 한계와 인문학
  
  
# Chapter 1 - 빅데이터 분석과 전략 인사이트 (Big Data Analytics and Strategic Insight)

## 1. 빅데이터 열풍과 회의론  

- "빨리 끓어 오른 냄비가 빨리 식는다?"
- 빅데이터 분석에서 찾을 수 있는 수많은 가치들을 제대로 발굴해 보기도 전에 그 활용 자체를 사전에 차단

## 2. 빅데이터 회의론의 원인 및 진단  

#### 가. 과거의 고객관계관리(CRM)  

- **공포 마케팅:** 도입만 하면 모든 문제를 한번에 해소할 것처럼 강조
- **거액 투자 및 하드웨어/솔루션 도입:** 어떻게 활용하고 가치를 뽑아내야 할지 난감

#### 나. 기존 분석 프로젝트를 포함한 빅데이터 성공사례 제조

- 국내 빅데이터 업체들이 CRM 분석 성과를 빅데이터 분석으로 과대포장
- 굳이 빅데이터가 필요 없는 경우 (우수 고객, 이탈 예측, 구매패턴 분석)

## 3. 빅데이터 분석, 'Big'이 핵심이 아니다  

- 데이터의 양이 아니라 유형의 **다양성**과 관련이 있다
- 데이터 크기 보다는 음성, 텍스트, 이미지, 비디오 같은 새롭고 **다양한 정보 원천의 활용**

## 4. 전략적 통찰이 없는 분석의 함정  

- 성과가 우수한 기업들도 가치 분석적 통찰력을 갖췄다고 대답단 비율이 매우 낮다
- 그만큼 기업의 핵심 가치와 관련해 전략적 통찰력을 가져다 주는 데이터 분석을 내재화 하는 것이 어렵다
- 단순히 분석을 많이 사용하는 것이 곧바로 경쟁우위를 가져다 주지는 않는다
  - 아메리칸 항공사의 복잡화, 최적화가 오히려 비즈니스에 마이너스
- 전략적 통찰력을 통한 핵심 비즈니스 이슈에 집중, 차별적인 전략 필요

## 5. 일차원적인 분석 vs 전략도출 위한 가치기반 분석  

#### 가. 1차원적 산업적 분석 애플리캐이션

- **금융:** 신용점수 산정, 사기 탐지, 고객 수익성 분석
- **제조업:** 맞춤형 상품 개발, 신상품 개발
- **병원:** 가격 책정, 고객 로열티, 수익 관리
- **정부:** 사기 탐지, 사례 관리, 범죄 방지, 수익 최적화
- **에너지:** 트레이딩, 공급, 수요 예측

#### 나. 일차적인 분석의 문제점

- 환경변화와 같은 큰 변화에 제대로 대응 X
- 새로운 기회 포착 힘듬

#### 다. 전략도출 가치기반 분석

- 해당 사업에 중요한 기회 발굴, 주요 경졍진의 지원 얻음
- 활용 범위를 더 넓고 전략적으로 변화
- 전략적 인사이트를 주는 가치기반 순석단계로 나아감
 
**예상문제**  
**14. 아래는 특정산업의 일차원적 분석 사례를 나열한 것이다. 다음 중 특정산업으로 적절한 것은?**  
<아래> 트레이딩, 공급, 수요 예측

1. 소매업  
2. 에너지  
3. 운송업  
4. 금융 서비스

(정답): 2번



# Chapter 2 - 전략 인사이트 도출을 위한 필요 역량 (Competency Needed to Drawing Strategic Insights)

## 1. 데이터 사이언스의 의미와 역할  

#### 가. 의미

- 데이터 공학, 수학, 통계학, 컴퓨터공학, 시각화 등 총체적 종합 학문
- 정형 또는 비정형을 막론하고 인터넷, 휴대전화, 감시용 카메라 등에서 생성되는 숫자와 문자, 영상 정보 등 다양한 유형의 데이터를 대상

#### 나. 역할

- 비즈니스 성과를 좌우하는 핵심이슈에 답하고 사업의 성과를 견인

## 2. 데이터 사이언스의 구성요소  

#### 가. 데이터 사이언스의 영역

- **IT (Data Management):** 시그널 프로세싱, 프로그래밍, 데이터 엔지니어링, 데이터 웨어하우스, 고성능 컴퓨팅 
- **Analytics (분석적 영역):** 수학, 확률모델, 머신러닝, 분석학, 패턴 인식과 학습, 불확실성 모델링 등
- **비즈니스 분석 (비즈니스 컨설팅 영역):** 커뮤니케이션, 프레젠테이션, 스토리텔링, 시각화 등

참고  

- **BI (Business Intelligence):** 데이터 기반 의사결정을 지원하기 위한 **리포트 중심**의 도구
- **BA (Business Analytics):** 의사결정을 위한 통계적이고 수학적인 분석에 초점

#### 나. 데이터 사이언티스트의 역할

- 강력한 호기심 가짐
- 스토리텔링, 커뮤니케이션, 창의력, 열정, 직관력, 비판적 시각, 글쓰기 능력, 대화 능력

## 3. 데이터 사이언티스트의 요구 역량  

- **Hard Skill** 
  - **빅데이터에 대한 이론적 지식:** 관련 기법에 대한 이해와 방법론 습득
  - **분석 기술에 대한 숙련:** 최적의 분석 설계 및 노하우 축적

- **Soft Skill**
  - **통찰력 있는 분석:** 창의적 사고, 호기심, 논리적 비판
  - **설득력 있는 전달:** 스토리텔링, Visualization
  - **다분야 간 협력:** Communication
  
- **Gartner의 데이트 사이언티스트의 역량**
  - 데이터 관리
  - 분석 모델링
  - 비즈니스 분석
  - 소프트 스킬  
  **-> 공통점은 호기심에서 시작**

## 4. 데이터 사이언스: 과학과 인문의 교차로  

- **인문학적 요소 필요:** 스토리텔링, 커뮤니케이션, 창의력, 열정, 직관력, 비판적 시각, 대화능력

## 5. 전략적 통찰력과 인문학의 부활  

- **단순세계화 -> 북잡한 세계화:** 다양성과 각 사회의 정체성과 그 맥락, 관계, 연결성, 창조성이 키워드로 대두
- **비즈니스의 중심 - 제품생산 -> 서비스:** 제품이 고장나더라도 뛰어난 고객 서비스를 제공해주는 것이 중요
- **경제와 산업의 논리 - 생산 -> 시장창조:** 새로운 현지화 패러다임에 근거한 시장 창조

**정보 (Information) vs 통찰력 (Insight)의 차이**  

- **정보** 
  - 과거: 무슨 일이 일어났는가? (리포팅/보고서)
  - 현재: 무슨 일이 일어나고 있는가? (경고)
  - 미래: 무슨 일이 일어날 것인가? (추출)

- **통찰력**
  - 과거: 어떻게, 왜 일어 났는가? (모델링)
  - 현재: 차선 행동은 무엇인가? (권고)
  - 미래: 최악, 최선의 상황은? (예측, 최적화)

**기출문제**  
**16. 데이터 사이언스와 데이터 사이언티스트에 대한 설명으로 부적절한 것은?**  

1. 통계학과 데이터 사이언스는 "데이터를 다룬다"는 점에서 유사하지만 통계학은 더욱 확장된 유형의 데이터를 근간으로 한다  
2. 데이터 사이언티스트가 갖춰야 할 역량으로 많은 전문가들은 호기심을 언급한다  
3. 더 높은 가치 창출과 차별화를 가져오는 것은 전략적 통찰력과 관련된 소프트 스킬이다  
4. 뛰어난 데이터 사이언티스트는 정량적 분석이라는 과학과 인문학적 통찰을 근거로 합리적 추론을 한다  

(정답): 1번

**기출문제**  
**17. 데이터 사이언스와 통계학이 다른 점을 나열하였다. 다음 중 가장 부적절 한 것은?**

1. 데이터 사이언스는 통계학과 달리 총제적 접근법을 사용한다
2. 정형 및 비정형을 포함한 다양한 유형의 데이터를 분석대상으로 한다
3. 분석뿐만 아니라 이를 효과적으로 구현하고 전달하는 과정까지 포함한다
4. 기존 통계학에 데이터마이닝을 접목한 새로운 융합 학문이다

(정답): 4번  
(해설): IT, Analytics, 비즈니스 분석 모두를 적용한 학문

**기출문제**  
**18. 다음 중 데이터 사이언티스트에게 요구도디는 소프트 역량이 아닌 것은?**

1. 이론적 지식
2. 창의적 사고
3. 커뮤니케이션 기술
4. 비쥬얼라이제이션을 활용한 설득력

(정답): 1번


# Chapter 3 - 빅데이터 그리고 데이터 사이언스의 미래 (The Future of Big Data and Data Science)

## 1. 빅데이터의 시대  

- 전 세계적으로 생성된 디지털 정보량이 2011년 기준 1.8 제타바이트에 이름

## 2. 빅데이터 회의론을 넘어 가치 패러다임의 변화  

- **과거 - 디지털화 (Digitalization):** 아날로그 세상을 어떻게 효과적으로 디질터화하는지가 과거의 가치 창출의 원천
- **현재 - 연결 (Connection):** 디지털화된 정보와 대상들은 서로 연결 시작, 연결을 더 효과적이고 효율적으로 제공하는가가 성공요인
- **미래 - 에이전시 (Agency):** 복잡한 연결을 얼마나 효율적이고 믿을 수 있게 관리하는가의 이슈

## 3. 데이터 사이언스의 한계와 인문학 

#### 가. 데이터 사이언스의 한계와 인문학

- 아무리 정량적인 분석이라도 모든 분석은 가정에 근거
- 분석과정에서는 가정 등 인간의 해석이 개입되는 단계를 반드시 거쳐야 함
- 분석결과가 의미하는 바는 사람에 따라 전혀 다른 해석과 결론을 내릴 수 있음

#### 나. 데이터 사이언스와 인문학

- 인문학을 이용하여 빅데이터와 데이터 사이언스가 데이터에 묻혀 있는 잠재력을 풀어내고, 새로운 기회를 찾고, 누구도 보지 못한 창조의 밑그림을 그릴 수 있는 힘을 발휘하게 될 것
